name: Run Embedding Cron Job

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours UTC
  workflow_dispatch:       # allow manual run

jobs:
  embed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_embeddings.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scripts/generate_embeddings.py
